package com.weixinpay.model;

public class DemoData{

	public static String WBJL="{"+
								"\"Code\":,"+
								"\"Message\":\"\","+
								"\"brand\":\"\","+
								"\"carComponentRecordsFlag\":1,"+
								"\"carConstructRecordsFlag\":1,"+
								"\"carFireFlag\":0,"+
								"\"carOutsideRecordsFlag\":1,"+
								"\"carType\":\"\","+
								"\"carWaterFlag\":0,"+
								"\"componentAnalyzeRepairRecords\":[{"+
								"\"content\":\"\","+
								"\"date\":\"\","+
								"\"mainTainDate\":null,"+
								"\"materal\":\"\","+
								"\"mileage\":55418,"+
								"\"payType\":null,"+
								"\"remark\":\";\","+
								"\"type\":\"\""+
								"}],"+
								"\"constructAnalyzeRepairRecords\":[{"+
								"\"content\":\"\","+
								"\"date\":\"2014-07-25\","+
								"\"mainTainDate\":1406299751000,"+
								"\"materal\":\"\","+
								"\"mileage\":55418,"+
								"\"payType\":null,"+
								"\"remark\":\";\","+
								"\"type\":\"自费\""+
								"}],"+
								"\"displacement\":\"8\","+
								"\"effluentStandard\":\"\","+
								"\"lastMainTainTime\":\"\","+
								"\"lastRepairTime\":\"\","+
								"\"mainTainTimes\":\"\","+
								"\"makeDate\":\"\","+
								"\"makeReportDate\":\"\","+
								"\"manufacturer\":\"\","+
								"\"mileageEstimate\":,"+
								"\"mileageEveryYear\":\"\","+
								"\"mileageIsNormalFlag\":1,"+
								"\"modelName\":\"MG6CAT\","+
								"\"normalRepairRecords\":[{"+
								"\"content\":\"\","+
								"\"date\":\"\","+
								"\"mainTainDate\":1318694426000,"+
								"\"materal\":\"\","+
								"\"mileage\":,"+
								"\"payType\":null,"+
								"\"remark\":null,"+
								"\"type\":\"\""+
								"},"+
								"{"+
								"\"content\":\"\","+
								"\"date\":\"2011-12-10\","+
								"\"mainTainDate\":1323528894000,"+
								"\"materal\":\"\","+
								"\"mileage\":,"+
								"\"payType\":null,"+
								"\"remark\":null,"+
								"\"type\":\"\""+
								"}"+
								"],"+
								"\"outsideAnalyzeRepairRecords\":[{"+
								"\"content\":\"\","+
								"\"date\":\"\","+
								"\"mainTainDate\":,"+
								"\"materal\":\"\","+
								"\"mileage\":1673,"+
								"\"payType\":null,"+
								"\"remark\":\";\","+
								"\"type\":\"\""+
								"}"+
								"],"+
								"\"productionArea\":null,"+
								"\"reportNo\":null,"+
								"\"seriesName\":\"\","+
								"\"transmissionType\":\"\","+
								"\"vin\":\"\""+
								"}";

}
